spring:
  profiles :
    active : dev

# 以下为开发环境
---
spring:
  profiles : dev


# 主数据源，默认的
  datasource:
      name: hikari
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://120.79.83.52:3306/dmsf_video?characterEncoding=utf8
      username: root
      password: admin
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 15
        auto-commit: true
        idle-timeout: 30000
        pool-name: DatebookHikariCP
        connection-test-query: SELECT 1
        max-lifetime: 1800000
        min-evictable-idle-time-millis: 300000
        connection-timeout: 30000


  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto : none
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect